[package]
name = "studio-patcher"
version = "0.7.4"
edition = "2024"

[[bin]]
name = "studio-patcher"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
anyhow = "1.0.104"
serde_json = "1.0.151"
zstd = "0.13.3"
regex = "1.13.1"
self-replace = "1.5.0"
luau-compile = { path = "crates/luau-compile" }

[profile.release]
opt-level = "z"
strip = true
codegen-units = 1
panic = "abort"
lto = true
